
#define             ID              1
#define             VAR             2
#define             CONST           3
#define             INT             4
#define             IF              5
#define             ELSE            6
#define             WHILE           7
#define             PRINT           8
#define             READ            9
#define             INTLITERAL      10
#define             LPAREN          11
#define             RPAREN          12
#define             PUNTOCOMA       13
#define             COMA            14
#define             IGUAL           15
#define             SUMA            16
#define             MENOS           17
#define 	    LCORCHETE	    18
#define 	    RCORCHETE	    19
#define 	    MULT	    20
#define             DIV             21
#define             INTERR          22
#define             DOSP            23
#define		    NUM	    	    24
#define		    STRING	    25
#define		    DO		    26
#define		    MENOR	    27
#define		    MAYOR	    28
#define		    MENORIGUAL	    29
#define		    MAYORIGUAL	    30
#define		    IGUALIGUAL	    31
#define		    DISTINTO        32
